# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created: Mon Jan 18 18:16:21 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 563)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 681, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 90, 661, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.salesStackPage = QtGui.QWidget()
        self.salesStackPage.setObjectName("salesStackPage")
        self.layoutWidget = QtGui.QWidget(self.salesStackPage)
        self.layoutWidget.setGeometry(QtCore.QRect(357, 20, 301, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.checkoutButton = QtGui.QPushButton(self.layoutWidget)
        self.checkoutButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkoutButton.setIcon(icon1)
        self.checkoutButton.setIconSize(QtCore.QSize(50, 50))
        self.checkoutButton.setObjectName("checkoutButton")
        self.gridLayout_3.addWidget(self.checkoutButton, 1, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.totalDisplay = QtGui.QLabel(self.layoutWidget)
        self.totalDisplay.setText("")
        self.totalDisplay.setObjectName("totalDisplay")
        self.gridLayout.addWidget(self.totalDisplay, 0, 1, 1, 2)
        self.balanceDisplayLbl = QtGui.QLabel(self.layoutWidget)
        self.balanceDisplayLbl.setText("")
        self.balanceDisplayLbl.setObjectName("balanceDisplayLbl")
        self.gridLayout.addWidget(self.balanceDisplayLbl, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.cashLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.cashLineEdit.setObjectName("cashLineEdit")
        self.gridLayout.addWidget(self.cashLineEdit, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 2)
        self.cartTableWidget = QtGui.QTableWidget(self.layoutWidget)
        self.cartTableWidget.setObjectName("cartTableWidget")
        self.cartTableWidget.setColumnCount(0)
        self.cartTableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.cartTableWidget, 0, 0, 1, 2)
        self.line_2 = QtGui.QFrame(self.salesStackPage)
        self.line_2.setGeometry(QtCore.QRect(320, 20, 20, 401))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget_2 = QtGui.QWidget(self.salesStackPage)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 20, 291, 401))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.searchButton = QtGui.QPushButton(self.layoutWidget_2)
        self.searchButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon2)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout_2.addWidget(self.searchButton, 0, 2, 1, 1)
        self.searchLineEdit = QtGui.QLineEdit(self.layoutWidget_2)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.gridLayout_2.addWidget(self.searchLineEdit, 0, 1, 1, 1)
        self.searchTableWidget = QtGui.QTableWidget(self.layoutWidget_2)
        self.searchTableWidget.setObjectName("searchTableWidget")
        self.searchTableWidget.setColumnCount(0)
        self.searchTableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.searchTableWidget, 1, 0, 1, 3)
        self.finishBtn = QtGui.QPushButton(self.salesStackPage)
        self.finishBtn.setGeometry(QtCore.QRect(570, 390, 89, 27))
        self.finishBtn.setObjectName("finishBtn")
        self.stackedWidget.addWidget(self.salesStackPage)
        self.notificationsPage = QtGui.QWidget()
        self.notificationsPage.setObjectName("notificationsPage")
        self.calendarWidget = QtGui.QCalendarWidget(self.notificationsPage)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 20, 421, 191))
        self.calendarWidget.setObjectName("calendarWidget")
        self.layoutWidget1 = QtGui.QWidget(self.notificationsPage)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 240, 311, 110))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.todaysSalesLCD = QtGui.QLCDNumber(self.layoutWidget1)
        self.todaysSalesLCD.setObjectName("todaysSalesLCD")
        self.verticalLayout_2.addWidget(self.todaysSalesLCD)
        self.stackedWidget.addWidget(self.notificationsPage)
        self.settingsStackPage = QtGui.QWidget()
        self.settingsStackPage.setObjectName("settingsStackPage")
        self.layoutWidget2 = QtGui.QWidget(self.settingsStackPage)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 345, 149))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.oldPwdLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.oldPwdLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.oldPwdLineEdit.setObjectName("oldPwdLineEdit")
        self.gridLayout_4.addWidget(self.oldPwdLineEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.newPwdLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.newPwdLineEdit.setObjectName("newPwdLineEdit")
        self.gridLayout_4.addWidget(self.newPwdLineEdit, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.rptNewPwdLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.rptNewPwdLineEdit.setObjectName("rptNewPwdLineEdit")
        self.gridLayout_4.addWidget(self.rptNewPwdLineEdit, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveSettingsBtn = QtGui.QPushButton(self.layoutWidget2)
        self.saveSettingsBtn.setObjectName("saveSettingsBtn")
        self.horizontalLayout_2.addWidget(self.saveSettingsBtn)
        self.cancelSettingsBtn = QtGui.QPushButton(self.layoutWidget2)
        self.cancelSettingsBtn.setObjectName("cancelSettingsBtn")
        self.horizontalLayout_2.addWidget(self.cancelSettingsBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.settingsStackPage)
        self.notificationsBtn = QtGui.QPushButton(self.centralwidget)
        self.notificationsBtn.setGeometry(QtCore.QRect(100, 10, 88, 67))
        self.notificationsBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notificationsBtn.setIcon(icon3)
        self.notificationsBtn.setIconSize(QtCore.QSize(58, 58))
        self.notificationsBtn.setObjectName("notificationsBtn")
        self.userSales = QtGui.QPushButton(self.centralwidget)
        self.userSales.setGeometry(QtCore.QRect(11, 12, 86, 65))
        self.userSales.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/makeSale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userSales.setIcon(icon4)
        self.userSales.setIconSize(QtCore.QSize(56, 56))
        self.userSales.setObjectName("userSales")
        self.userLogout = QtGui.QPushButton(self.centralwidget)
        self.userLogout.setGeometry(QtCore.QRect(585, 11, 88, 67))
        self.userLogout.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userLogout.setIcon(icon5)
        self.userLogout.setIconSize(QtCore.QSize(58, 58))
        self.userLogout.setObjectName("userLogout")
        self.userSettings = QtGui.QPushButton(self.centralwidget)
        self.userSettings.setGeometry(QtCore.QRect(190, 10, 88, 67))
        self.userSettings.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userSettings.setIcon(icon6)
        self.userSettings.setIconSize(QtCore.QSize(58, 58))
        self.userSettings.setObjectName("userSettings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Point of Sale System", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Cash:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Balance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search: ", None, QtGui.QApplication.UnicodeUTF8))
        self.finishBtn.setText(QtGui.QApplication.translate("MainWindow", "Finish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Total Sales", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Change Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Old Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "New Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Repeat New Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelSettingsBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import qrc_resources
